//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamDAL.DBContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OnlineExamEntities : DbContext
    {
        public OnlineExamEntities()
            : base("name=OnlineExamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Register> Registers { get; set; }
        public virtual DbSet<SubjectDetail> SubjectDetails { get; set; }
        public virtual DbSet<tblQuestionTransaction> tblQuestionTransactions { get; set; }
        public virtual DbSet<Result> Results { get; set; }
    
        public virtual ObjectResult<Get_QuestionById_Result> Get_QuestionById(Nullable<int> getQuestionId)
        {
            var getQuestionIdParameter = getQuestionId.HasValue ?
                new ObjectParameter("GetQuestionId", getQuestionId) :
                new ObjectParameter("GetQuestionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_QuestionById_Result>("Get_QuestionById", getQuestionIdParameter);
        }
    }
}
