//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageDAL.ContextDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ApplicationDBEntities : DbContext
    {
        public ApplicationDBEntities()
            : base("name=ApplicationDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblManageUser> tblManageUsers { get; set; }
        public virtual DbSet<tblQuestionBank> tblQuestionBanks { get; set; }
        public virtual DbSet<tblResultRecord> tblResultRecords { get; set; }
        public virtual DbSet<tblRoleMaster> tblRoleMasters { get; set; }
        public virtual DbSet<tblSubjectDetail> tblSubjectDetails { get; set; }
        public virtual DbSet<tblUserAnswer> tblUserAnswers { get; set; }
    
        public virtual ObjectResult<SP_GetResult_Result> SP_GetResult(Nullable<int> subject_ID, string userName)
        {
            var subject_IDParameter = subject_ID.HasValue ?
                new ObjectParameter("Subject_ID", subject_ID) :
                new ObjectParameter("Subject_ID", typeof(int));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetResult_Result>("SP_GetResult", subject_IDParameter, userNameParameter);
        }
    
        public virtual ObjectResult<Sp_GetRoleById_Result> Sp_GetRoleById(Nullable<int> role_Id)
        {
            var role_IdParameter = role_Id.HasValue ?
                new ObjectParameter("Role_Id", role_Id) :
                new ObjectParameter("Role_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetRoleById_Result>("Sp_GetRoleById", role_IdParameter);
        }
    
        public virtual ObjectResult<sp_GetStudentTestDetails_Result> sp_GetStudentTestDetails(Nullable<int> subject_Id)
        {
            var subject_IdParameter = subject_Id.HasValue ?
                new ObjectParameter("Subject_Id", subject_Id) :
                new ObjectParameter("Subject_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetStudentTestDetails_Result>("sp_GetStudentTestDetails", subject_IdParameter);
        }
    
        public virtual ObjectResult<SP_GetUserDetail_Result> SP_GetUserDetail(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetUserDetail_Result>("SP_GetUserDetail", userNameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<SP_GetUserNameDetail_Result> SP_GetUserNameDetail(string userName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetUserNameDetail_Result>("SP_GetUserNameDetail", userNameParameter);
        }
    
        public virtual ObjectResult<Sp_Questionbank_Detail_Result> Sp_Questionbank_Detail(Nullable<int> subject_Id)
        {
            var subject_IdParameter = subject_Id.HasValue ?
                new ObjectParameter("Subject_Id", subject_Id) :
                new ObjectParameter("Subject_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Questionbank_Detail_Result>("Sp_Questionbank_Detail", subject_IdParameter);
        }
    
        public virtual ObjectResult<SP_GetResultByUserName_Result> SP_GetResultByUserName(string userName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetResultByUserName_Result>("SP_GetResultByUserName", userNameParameter);
        }
    }
}
