//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageDAL.ContextDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResultRecord
    {
        public int Result_ID { get; set; }
        public Nullable<int> Subject_Id { get; set; }
        public string UserName { get; set; }
        public string SubjectName { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string SubjectMarks { get; set; }
        public Nullable<int> TestMarks { get; set; }
    }
}
