//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageDAL.ContextDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserAnswer
    {
        public int ST_Id { get; set; }
        public Nullable<int> Subject_Id { get; set; }
        public string UserName { get; set; }
        public Nullable<int> Question_Id { get; set; }
        public string AnswerGiven { get; set; }
        public string CorrectAnswer { get; set; }
        public Nullable<bool> IsAnswerCorrect { get; set; }
        public Nullable<int> TestMarks { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
