//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineExamEntities1 : DbContext
    {
        public OnlineExamEntities1()
            : base("name=OnlineExamEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Register> Registers { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<SubjectDetail> SubjectDetails { get; set; }
    }
}
