//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectDetail
    {
        public int Subject_id { get; set; }
        public string Subject_name { get; set; }
        public Nullable<decimal> Subject_Marks { get; set; }
        public Nullable<int> User_id { get; set; }
    }
}
